name: xeus-kernel
channels:
  - https://repo.prefix.dev/emscripten-forge-dev
  - https://repo.prefix.dev/conda-forge
dependencies:
  - xeus-python
  - xeus-cpp
  - numpy
  - scipy
  - matplotlib
  - autograd
  - tqdm
  - scikit-learn
  - ipywidgets
  - joblib
  - setuptools

